### ISSUE TITLE
Ready to use IPKG for luci-app-knxd

### ISSUE THREAD

**Issue by martenumberto** [stargieg/packages-automation#7]
Hey!

This is not an issue, but is it possible to provide a ready to use IPKG package for luci-app-knxd?
I'm looking forward to chance the Settings very simple over a gui instead of manually editing the knxd.ini
Thx for this work!

**Comment by stargieg** [comment]
Hi
This is untested but it could work.
Install way: A
```
cd /etc/opkg/keys/
wget http://feeds.lunatiki.de/packages-automation/152ccf91cd6bfbdd
echo 'src/gz packages_automation http://feeds.lunatiki.de/packages-automation/' >> /etc/opkg/customfeeds.conf
opkg update
opkg install luci-app-knxd
```
Install way: B
```
opkg update
opkg install http://feeds.lunatiki.de/packages-automation/luci-app-knxd_0.2.6-2_all.ipk
```
PS: Short test OK

**Comment by martenumberto** [comment]
Thx for your fast help!
"knxd Diagnostics" opens up in Luci. But the normal "knxd" menu entry doesnt work.
`/usr/lib/lua/luci/dispatcher.lua:1379: module 'luci.cbi' not found:
	no field package.preload['luci.cbi']
	no file './luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi.lua'
	no file '/usr/share/lua/luci/cbi/init.lua'
	no file '/usr/lib/lua/luci/cbi.lua'
	no file '/usr/lib/lua/luci/cbi/init.lua'
	no file './luci/cbi.so'
	no file '/usr/lib/lua/luci/cbi.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/dispatcher.lua:1379: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1056: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>`
Can you give me any tipps?

**Comment by stargieg** [comment]
Wich openwrt version?
try
```
opkg install luci-compat
```

**Comment by martenumberto** [comment]
Thank you very much!
It was a custom build from the OpenWrt Firmware Selector. I installed luci-compat and it works pretty well on the first look.
Version is 22.03.3
